spring:
  datasource:
    url: jdbc:mysql://hanghe-database.cla4iewkenyo.ap-northeast-2.rds.amazonaws.com:3306/hanghe?useSSL=false
    username: hanghe
    password: hanghe1212
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    serialization:
      write-null-map-values: true

  jpa:
    show-sql: true

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level :
    com.hanghe : INFO
  charset:
    console: UTF-8
    file: UTF-8
